services:
  db:
    image: mysql:8.0
    container_name: linkshare-mysql-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: linkShare
    ports:
      - "3306:3306"
    volumes:
      - link-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: links-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD:
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  link-db-data: